travis:
  secure:
    BINSTAR_TOKEN: YDDOBGwYzlw7VEbEwFwd2Ocql/4zQKd+jHKiSgcPpqTqWF2dznkoDrh8p9qsXwQOB36FdLLGxzAyjaQlZEAYIRXj/k/+rSQyoGT50qPZfazuqhWN0okhaJ+VZo2iH/wh6L9XQ/gpSvtFPI3khhLP2I5wi+XkfHz3coSQDxjVlokXpu8nhPAjqjpmGlp9ttT+t2jybog+4aYiq4rO9A7DPt548tNswkX+Uz4A4GAl56km0/EbGZtA4wgnLP6HgpgNBRO7QLAmlVThIgKOI5f6nRDeixp0qWGCAw7z8ekpKLyanbZDr9atxtro9OZV9ycEMvL2HPzUPAYdhlTEri+rBbGMWXmr8yYZ4kCVjWtfM4g8GYJejMx7G70XKpHlsNkDRZVPRgvETQktDGPPGpoDCw/Jt9J02ctpf/R9JuM98rFatpnT4TgqVlGTyMeDfkNyzCyaxAhdC8jSXBp6dgA5YNPn/VluPmnOxO29Cd+orVhD513F7t8PgS3WH2VgXzFAF3YlFS940r9ll6PdcMwcPPWchOmVMPWW5fi2SZykI/4GIrrt2+5dLjo9fnQG/cVyGXighemYoLbNFL5rgbGFdRydetKC06GREdkFzx+0mwR5GoDlhUOQZsnqBNyhS4Nkr+w/P3rcWKgEg4zgCgf8rvTP4Ms9WqHKREAwzPKLX+I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
